version: "3.7"

services:
  database_finapi:
    image: postgres
    container_name: database_finapi
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=ignite
      - POSTGRES_DB=finapi
    volumes:
      - pgdata:/data/postgres
  app:
    build: .
    container_name: finapi
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_finapi
    depends_on:
      - database_finapi


volumes:
  pgdata:
    driver: local
